# This workflow will install Python dependencies, run tests with pytests provided in the appropriate dirtory

name: Python package

on:
  push:
    branches: [ "enh/poetry_test_/#14" ]
  pull_request:
    branches: [ "enh/poetry_test_/#14" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.9"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install opencv-python==4.9.0.80 pytest numpy==1.26.4 pillow==10.2.0 networkx==3.2.1
        python -m pip install torchsummary==1.5.1 facenet-pytorch==2.5.3
        python -m pip install torch==2.4.1 torchvision==0.19.1 --index-url https://download.pytorch.org/whl/cu118
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest tests/
